### ISSUE TITLE
CI: config specification

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#12297]
We need to be able to specify "`ubuntu22` combined with `-DDLLVM_BUILD_TYPE=Debug -Dsoversion=On`". Ideally we can trigger such a bit from a PR commit.

Also for the matrix specified in `.github/workflows/buildroot.yml`:
```yaml
    strategy:
      matrix:
        image: ["fedora37", "centos8", "ubuntu18", "ubuntu20", "ubuntu22"]
        config: ["Release"]
```
we want to specify the flags. We discussed changing this to a list; for me, `["ubuntu22", "-DDLLVM_BUILD_TYPE=Debug", "-Dsoversion=On"]` would work well as a replacement for the current `"ubuntu22"` entry.
